### ISSUE TITLE
Google pay error on completeCardEntry

### ISSUE THREAD

**Issue by mohisham** [square/in-app-payments-flutter-plugin#118]
I am using Google pay to make a transaction, and everything works great until I call `await InAppPayments.completeCardEntry();` and then I get an error.  

  Here is the log:
  ```
E/MethodChannel#square_in_app_payments(19582): Failed to handle method call
E/MethodChannel#square_in_app_payments(19582): java.lang.NullPointerException: Attempt to invoke virtual method 'void java.util.concurrent.CountDownLatch.countDown()' on a null object reference
E/MethodChannel#square_in_app_payments(19582): 	at sqip.flutter.internal.CardEntryModule.completeCardEntry(CardEntryModule.java:159)
E/MethodChannel#square_in_app_payments(19582): 	at sqip.flutter.SquareInAppPaymentsFlutterPlugin.onMethodCall(SquareInAppPaymentsFlutterPlugin.java:64)
E/MethodChannel#square_in_app_payments(19582): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:226)
E/MethodChannel#square_in_app_payments(19582): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/MethodChannel#square_in_app_payments(19582): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:631)
E/MethodChannel#square_in_app_payments(19582): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#square_in_app_payments(19582): 	at android.os.MessageQueue.next(MessageQueue.java:336)
E/MethodChannel#square_in_app_payments(19582): 	at android.os.Looper.loop(Looper.java:174)
E/MethodChannel#square_in_app_payments(19582): 	at android.app.ActivityThread.main(ActivityThread.java:7356)
E/MethodChannel#square_in_app_payments(19582): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#square_in_app_payments(19582): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
E/MethodChannel#square_in_app_payments(19582): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)

  ```

`flutter doctor -v` log:

```
[✓] Flutter (Channel stable, v1.17.3, on Mac OS X 10.15.4 19E287, locale en-CA)
    • Flutter version 1.17.3 at /Users/hmhm/Development/flutter
    • Framework revision b041144f83 (4 weeks ago), 2020-06-04 09:26:11 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/hmhm/Library/Android/sdk
    • Platform android-29, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4.1, Build version 11E503a
    • CocoaPods version 1.9.1

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.8052
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[!] IntelliJ IDEA Community Edition (version 2020.1.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[✓] VS Code (version 1.43.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.4.1

[✓] Connected device (2 available)
    • Pixel 3 XL        • 8B3Y0TGM3                            • android-arm64 • Android 10 (API 29)
    • iPhone 11 Pro Max • 0FE92F2D-FDCA-4226-AB65-026AA60CFF57 • ios           • com.apple.CoreSimulator.SimRuntime.iOS-13-4 (simulator)

! Doctor found issues in 1 category.

```

**Comment by mohsin-sq** [comment]
Hi @mohisham ,

Are you still facing this issue? Is this with the example application? Could you share the version of the SDK you are using?

**Comment by mohisham** [comment]
Yes I am still having this issue, I am using square_in_app_payments: 1.4.0

No problems on iOS btw.

**Comment by mohsin-sq** [comment]
Ah yes, that is because they introduced a new brand type that has been silently breaking the nonce conversion. I have a PR out that i'll merge tomorrow which should fix this issue! I'll follow up shortly!

**Comment by mohsin-sq** [comment]
The code change were pushed to the repo, will update the package manager soon. If you would like to validate your application gets fixed with the latest changes, you can clone the github repo and validate.

**Comment by mohsin-sq** [comment]
The changes have been pushed to the package manager. Please upgrade to the latest version of the plugin and see if that has fixed your issue! Let me know if you have any concerns!

**Comment by mohsin-sq** [comment]
I'll be closing this as the issue should be resolved. Please feel free to re-open if something changes!
