### ISSUE TITLE
Android crash when hitting back button or after square card entry complete in release mode ( Square )

### ISSUE THREAD

**Issue by HoangNam3202** [square/in-app-payments-flutter-plugin#199]
E/AndroidRuntime(30435): FATAL EXCEPTION: EventsUploadThread
E/AndroidRuntime(30435): Process, PID: 30435
E/AndroidRuntime(30435): java.lang.IllegalArgumentException: Method return type must not include a type variable or wildcard: o.b<?>
E/AndroidRuntime(30435):     for method h.a
E/AndroidRuntime(30435):        at o.w.o(Unknown Source:46)
E/AndroidRuntime(30435):        at o.w.n(Unknown Source:1)
E/AndroidRuntime(30435):        at o.t.b(Unknown Source:40)
E/AndroidRuntime(30435):        at o.s.d(Unknown Source:24)
E/AndroidRuntime(30435):        at o.s$a.invoke(Unknown Source:32)
E/AndroidRuntime(30435):        at java.lang.reflect.Proxy.invoke(Proxy.java:913)
E/AndroidRuntime(30435):        at $Proxy1.a(Unknown Source)
E/AndroidRuntime(30435):        at sqip.internal.j1.a$a.l(Unknown Source:68)
E/AndroidRuntime(30435):        at sqip.internal.j1.a$a.f(Unknown Source:0)
E/AndroidRuntime(30435):        at sqip.internal.j1.a$a$b.run(Unknown Source:4)
E/AndroidRuntime(30435):        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)       
E/AndroidRuntime(30435):        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)       
E/AndroidRuntime(30435):        at java.lang.Thread.run(Thread.java:764)

square_in_app_payments 1.7.1
flutter version : 2.10.3
Dart SDK version: 2.16.1

**Comment by HoangNam3202** [comment]
Solved by : 
useProguard false
minifyEnabled false
shrinkResources false

buildTypes {
        debug {
            signingConfig signingConfigs.debug
        }
        release {
            signingConfig signingConfigs.release
            useProguard false
            minifyEnabled false
            shrinkResources false
        }
    }
