### ISSUE TITLE
Unable to find a specification for `SquareInAppPaymentsSDK (= 1.1.1)` depended upon by `square_in_app_payments`

### ISSUE THREAD

**Issue by ronparkdeveloper** [square/in-app-payments-flutter-plugin#42]
Hello Square,

I'm trying to build my own app and also run the Square Flutter example app but because of this error in this post's title, I'm unable to get a build going. I downloaded the example file and went by the get started instructions which were all done today, 4/2/2019.

On my own app, I edited the pubspec.yaml file to be: square_in_app_payments: 1.1.0 instead of ^1.1.0. This got the build to work, but I'd rather go by the latest version available.

On the example app, I don't know how to edit such value since it seems to be that the Square SDK files are part of the project, and I can't find any ^1.1.0 value anywhere for me to just tinker around with.

I saw that the iOS github repo is versioned at 1.1.1, so I'm not sure why I'm facing the build errors.

The complete build log is here:

```
Launching lib/main.dart on iPhone X in debug mode...
Running pod install...
CocoaPods' output:
↳
      Preparing

    Analyzing dependencies

    Inspecting targets to integrate
      Using `ARCHS` setting to build architectures of target `Pods-Runner`: (``)

    Finding Podfile changes
      - Flutter
      - square_in_app_payments

    Fetching external sources
    -> Fetching podspec for `Flutter` from `.symlinks/flutter/ios`
    -> Fetching podspec for `square_in_app_payments` from `.symlinks/plugins/square_in_app_payments/ios`

    Resolving dependencies of `Podfile`
    [!] Unable to find a specification for `SquareInAppPaymentsSDK (= 1.1.1)` depended upon by `square_in_app_payments`

    /usr/local/Cellar/cocoapods/1.5.3/libexec/gems/cocoapods-1.5.3/lib/cocoapods/resolver.rb:402:in `find_cached_set'
    /usr/local/Cellar/cocoapods/1.5.3/libexec/gems/cocoapods-1.5.3/lib/cocoapods/resolver.rb:372:in `specifications_for_dependency'
    /usr/local/Cellar/cocoapods/1.5.3/libexec/gems/cocoapods-1.5.3/lib/cocoapods/resolver.rb:177:in `search_for'
    /usr/local/Cellar/cocoapods/1.5.3/libexec/gems/cocoapods-1.5.3/lib/cocoapods/resolver.rb:288:in `block in sort_dependencies'
    /usr/local/Cellar/cocoapods/1.5.3/libexec/gems/cocoapods-1.5.3/lib/cocoapods/resolver.rb:281:in `each'
    /usr/local/Cellar/cocoapods/1.5.3/libexec/gems/cocoapods-1.5.3/lib/cocoapods/resolver.rb:281:in `sort_by'
    /usr/local/Cellar/cocoapods/1.5.3/libexec/gems/cocoapods-1.5.3/lib/cocoapods/resolver.rb:281:in `sort_dependencies'
    /usr/local/Cellar/cocoapods/1.5.3/libexec/gems/molinillo-0.6.6/lib/molinillo/delegates/specification_provider.rb:53:in `block in sort_dependencies'
    /usr/local/Cellar/cocoapods/1.5.3/libexec/gems/molinillo-0.6.6/lib/molinillo/delegates/specification_provider.rb:70:in `with_no_such_dependency_error_handling'
    /usr/local/Cellar/cocoapods/1.5.3/libexec/gems/molinillo-0.6.6/lib/molinillo/delegates/specification_provider.rb:52:in `sort_dependencies'
    /usr/local/Cellar/cocoapods/1.5.3/libexec/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:754:in `push_state_for_requirements'
    /usr/local/Cellar/cocoapods/1.5.3/libexec/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:746:in `require_nested_dependencies_for'
    /usr/local/Cellar/cocoapods/1.5.3/libexec/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:729:in `activate_new_spec'
    /usr/local/Cellar/cocoapods/1.5.3/libexec/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:686:in `attempt_to_activate'
    /usr/local/Cellar/cocoapods/1.5.3/libexec/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:254:in `process_topmost_state'
    /usr/local/Cellar/cocoapods/1.5.3/libexec/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:182:in `resolve'
    /usr/local/Cellar/cocoapods/1.5.3/libexec/gems/molinillo-0.6.6/lib/molinillo/resolver.rb:43:in `resolve'
    /usr/local/Cellar/cocoapods/1.5.3/libexec/gems/cocoapods-1.5.3/lib/cocoapods/resolver.rb:123:in `resolve'
    /usr/local/Cellar/cocoapods/1.5.3/libexec/gems/cocoapods-1.5.3/lib/cocoapods/installer/analyzer.rb:781:in `block in resolve_dependencies'
    /usr/local/Cellar/cocoapods/1.5.3/libexec/gems/cocoapods-1.5.3/lib/cocoapods/user_interface.rb:64:in `section'
    /usr/local/Cellar/cocoapods/1.5.3/libexec/gems/cocoapods-1.5.3/lib/cocoapods/installer/analyzer.rb:779:in `resolve_dependencies'
    /usr/local/Cellar/cocoapods/1.5.3/libexec/gems/cocoapods-1.5.3/lib/cocoapods/installer/analyzer.rb:88:in `analyze'
    /usr/local/Cellar/cocoapods/1.5.3/libexec/gems/cocoapods-1.5.3/lib/cocoapods/installer.rb:243:in `analyze'
    /usr/local/Cellar/cocoapods/1.5.3/libexec/gems/cocoapods-1.5.3/lib/cocoapods/installer.rb:154:in `block in resolve_dependencies'
    /usr/local/Cellar/cocoapods/1.5.3/libexec/gems/cocoapods-1.5.3/lib/cocoapods/user_interface.rb:64:in `section'
    /usr/local/Cellar/cocoapods/1.5.3/libexec/gems/cocoapods-1.5.3/lib/cocoapods/installer.rb:153:in `resolve_dependencies'
    /usr/local/Cellar/cocoapods/1.5.3/libexec/gems/cocoapods-1.5.3/lib/cocoapods/installer.rb:116:in `install!'
    /usr/local/Cellar/cocoapods/1.5.3/libexec/gems/cocoapods-1.5.3/lib/cocoapods/command/install.rb:41:in `run'
    /usr/local/Cellar/cocoapods/1.5.3/libexec/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
    /usr/local/Cellar/cocoapods/1.5.3/libexec/gems/cocoapods-1.5.3/lib/cocoapods/command.rb:52:in `run'
    /usr/local/Cellar/cocoapods/1.5.3/libexec/gems/cocoapods-1.5.3/bin/pod:55:in `<top (required)>'
    /usr/local/Cellar/cocoapods/1.5.3/libexec/bin/pod:22:in `load'
    /usr/local/Cellar/cocoapods/1.5.3/libexec/bin/pod:22:in `<main>'

Error running pod install
Error launching application on iPhone X.
```

Thank you for your help in advance.

**Comment by hukid** [comment]
@ronparkdeveloper can you try to update your pod repo by running `pod repo update`? I had same issue and this command worked.

**Comment by ronparkdeveloper** [comment]
Thank you, @hukid. After dealing with some headaches on Cocoapod betas I've been afraid of messing with it, and I totally lost the thought of running any pod updates. I was able to run my own program and the Square sample project. Hopefully my ticket can help out others in the same shoes.
