### ISSUE TITLE
Occasional Hard Crash in onCardNonceSuccess on Android

### ISSUE THREAD

**Issue by d3vtoolsmith** [square/in-app-payments-flutter-plugin#54]
This hard crash happens rarely to our Android users. Does one of the recent updates happen to fix this specific issue or is it something else?
Thank you

```
Fatal Exception: java.lang.RuntimeException: Methods marked with @UiThread must be executed on the main thread. Current thread: CardResultHandler
       at io.flutter.embedding.engine.FlutterJNI.ensureRunningOnMainThread(FlutterJNI.java:36)
       at io.flutter.embedding.engine.FlutterJNI.dispatchPlatformMessage(FlutterJNI.java)
       at io.flutter.embedding.engine.dart.DartMessenger.send(DartMessenger.java:60)
       at io.flutter.embedding.engine.dart.DartMessenger.send(DartMessenger.java:60)
       at io.flutter.embedding.engine.dart.DartExecutor.send(DartExecutor.java:2)
       at io.flutter.embedding.engine.dart.DartExecutor.send(DartExecutor.java:2)
       at io.flutter.view.FlutterNativeView.send(FlutterNativeView.java:31)
       at io.flutter.view.FlutterNativeView.send(FlutterNativeView.java:31)
       at io.flutter.plugin.common.MethodChannel.invokeMethod(MethodChannel.java:24)
       at io.flutter.plugin.common.MethodChannel.invokeMethod(MethodChannel.java:24)
       at io.flutter.plugin.common.MethodChannel.invokeMethod(MethodChannel.java:1)
       at io.flutter.plugin.common.MethodChannel.invokeMethod(MethodChannel.java:1)
       at sqip.flutter.internal.CardEntryModule$2.handleEnteredCardInBackground(CardEntryModule.java:25)
       at sqip.internal.CardEntryActivityController$onCardNonceSuccess$1.run(CardEntryActivityController.java:6)
       at java.util.concurrent.ThreadPoolExecutor.runWorker + 1167(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run + 641(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run + 919(Thread.java:919)
```

**Comment by hukid** [comment]
@d3vtoolsmith Have you updated the plugin to latest version? this seems related to #50 which has been fixed in the latest plugin.

**Comment by d3vtoolsmith** [comment]
Oh, fabulous. I was one version behind. Testing it one in the next day or two, hopefully that's it.
Thank you!
