### ISSUE TITLE
FormatException when decoding the json.

### ISSUE THREAD

**Issue by mikeyyg96** [square/in-app-payments-flutter-plugin#60]
### Describe the issue
I was following the documentation on setting up the payment processing. Everything looks good except when the user saves the valid card, I get a FormatException when decoding the json. It looks just like the documentation so I am confused if I am missing something.
  
  Here is the log:
  ```
  E/flutter ( 7392): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: FormatException: Unexpected character (at character 1)
E/flutter ( 7392): <!DOCTYPE html>
E/flutter ( 7392): ^
E/flutter ( 7392):
E/flutter ( 7392): #0      _ChunkedJsonParser.fail  (dart:convert-patch/convert_patch.dart:1392:5)
E/flutter ( 7392): #1      _ChunkedJsonParser.parseNumber  (dart:convert-patch/convert_patch.dart:1259:9)
E/flutter ( 7392): #2      _ChunkedJsonParser.parse  (dart:convert-patch/convert_patch.dart:924:22)
E/flutter ( 7392): #3      _parseJson  (dart:convert-patch/convert_patch.dart:29:10)
E/flutter ( 7392): #4      JsonDecoder.convert  (dart:convert/json.dart:493:36)
E/flutter ( 7392): #5      JsonCodec.decode  (dart:convert/json.dart:151:41)
E/flutter ( 7392): #6      _EventLayoutState.chargeCard 
package:link/…/events_list/list_page.dart:422
E/flutter ( 7392): <asynchronous suspension>
E/flutter ( 7392): #7      _EventLayoutState._makeCharge 
package:link/…/events_list/list_page.dart:436
E/flutter ( 7392): <asynchronous suspension>
E/flutter ( 7392): #8      _EventLayoutState._cardNonceRequestSuccess 
package:link/…/events_list/list_page.dart:403
E/flutter ( 7392): #9      InAppPayments._nativeCallHandler 
package:square_in_app_payments/in_app_payments.dart:77
E/flutter ( 7392): <asynchronous suspension>
E/flutter ( 7392): #10     MethodChannel._handleAsMethodCall 
package:flutter/…/services/platform_channel.dart:397
E/flutter ( 7392): <asynchronous suspension>
E/flutter ( 7392): #11     MethodChannel.setMethodCallHandler.<anonymous closure> 
package:flutter/…/services/platform_channel.dart:365
E/flutter ( 7392): #12     _DefaultBinaryMessenger.handlePlatformMessage 
package:flutter/…/services/binary_messenger.dart:110
E/flutter ( 7392): <asynchronous suspension>
E/flutter ( 7392): #13     _invoke3.<anonymous closure>  (dart:ui/hooks.dart:280:15)
E/flutter ( 7392): #14     _rootRun  (dart:async/zone.dart:1124:13)
E/flutter ( 7392): #15     _CustomZone.run  (dart:async/zone.dart:1021:19)
E/flutter ( 7392): #16     _CustomZone.runGuarded  (dart:async/zone.dart:923:7)
E/flutter ( 7392): #17     _invoke3  (dart:ui/hooks.dart:279:10)

  ```
-->

### To Reproduce
  Steps to reproduce the issue.
  1) Read the documentation [https://github.com/square/in-app-payments-flutter-plugin/blob/master/example/take_a_payment.md](url)
  2) Call the function InAppPayments.startCardEntryFlow()
  3) Complete form and get a nonce
  4) Make the charge (which I still don't know how to set a PRICE to the transaction using Heroku)
  5) Pass in the CardDetails result and the chargeUrl string.

  Here the piece of code that reproduce the issue.
  ```dart
    Future<void> chargeCard(CardDetails result, String chargeUrl) async {
    var body = jsonEncode({"nonce": result.nonce});
    http.Response response;
    try {
      response = await http.post(chargeUrl, body: body, headers: {
        "Accept": "application/json",
        "content-type": "application/json"
      });
    } on SocketException catch (ex) {
      throw ChargeException(ex.message);
    }

    var responseBody = json.decode(response.body); // FormatException occurs 
    if (response.statusCode == 200) {
      return;
    } else {
      throw ChargeException(responseBody["errorMessage"]);
    }
  }
  ```

### Expected behavior
To make a transaction and NOT break the app. Also want to pass in a PRICE variable but don't know how to do it.

**Environment (please complete the following information):**
  - platform: Android
  - OnePlus 6T OxygenOS version 9.0.16
  - Windows
  - square_in_app_payments: ^1.2.2

  ```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.7.8+hotfix.4, on Microsoft Windows [Version 10.0.17763.678], locale en-US)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[!] Android Studio (version 3.4)
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
[√] VS Code (version 1.37.1)
[√] Connected device (1 available)

! Doctor found issues in 1 category.
  ```

### Screenshots
![Json Decoder](https://user-images.githubusercontent.com/33616962/63900610-0329e000-c9cf-11e9-806b-6e28979cc5a7.png)

### Additional context
I should note that a transaction of $0.01 did occur but not fully. It has been refunded.

**Comment by StephenJosey** [comment]
Hi @mikeyyg96 were you able to successfully set up the quick start Heroku backend and it's running? When debugging, can you see what "response.body" is actually set to? Also, if you login to your Heroku account, can you check the logs and see what it is returning to your app?

Also, what is your `chargeUrl` variable set to?

**Comment by mikeyyg96** [comment]
@StephenJosey I wasn't able to set it up. I am still looking for help. I am just following step-by-step on the documenation.

Response Body Output:
`I/flutter (22299): (debug) response.body is: <!DOCTYPE html>`

My Variable `chargeUrl`:
`String chargeUrl = "$chargeServerHost/chargeForCookie";`

My Heroku Log:
```
2019-08-28T23:44:24.364409+00:00 app[web.1]: 
2019-08-28T23:44:24.815277+00:00 app[web.1]: Your app is listening on port 55252
2019-08-28T23:44:25.701997+00:00 heroku[web.1]: State changed from starting to up
2019-08-28T23:44:26.312799+00:00 heroku[router]: at=info method=POST path="//chargeForCookie" host=links-app-maginate.herokuapp.com request_id=914d9cc7-3498-45ad-9013-7e5576ea8636 fwd="73.52.103.100" dyno=web.1 connect=0ms service=27ms status=404 bytes=400 protocol=https
2019-08-28T23:47:00.321851+00:00 heroku[router]: at=info method=POST path="//chargeForCookie" host=links-app-maginate.herokuapp.com request_id=00bdf869-bd41-4a78-bf00-121f676f590d fwd="73.52.103.100" dyno=web.1 connect=0ms service=4ms status=404 bytes=400 protocol=https
2019-08-28T23:57:01.639212+00:00 heroku[router]: at=info method=POST path="//chargeForCookie" host=links-app-maginate.herokuapp.com request_id=[a7c8ea43-8e41-42df-8326-cb1b98886ff1] fwd="73.52.103.100" dyno=web.1 connect=0ms service=2ms status=404 bytes=400 protocol=https
2019-08-29T00:33:32.027800+00:00 heroku[web.1]: Idling
2019-08-29T00:33:32.034705+00:00 heroku[web.1]: State changed from up to down
2019-08-29T00:33:33.511985+00:00 heroku[web.1]: Stopping all processes with SIGTERM
2019-08-29T00:33:33.665263+00:00 heroku[web.1]: Process exited with status 143
```

**Comment by StephenJosey** [comment]
Hm, and what is `$chargeServerHost`? From the heroku logs it appears that there may be a double "/" in the path, so you might need to remove one of those. (either from `chargeUrl` or `chargeServerHost` if both have it).

**Comment by mikeyyg96** [comment]
I just got a ChargeException when I removed the '/'

OLD:
`String chargeServerHost = "https://links-app-maginate.herokuapp.com/";`
`String chargeUrl = "$chargeServerHost/chargeForCookie";`

NEW:
`String chargeServerHost = "https://links-app-maginate.herokuapp.com"; // remove`
`String chargeUrl = "$chargeServerHost/chargeForCookie";`

Exception:
`I/flutter (22299): (debug) response.body is: {"errorMessage":"Payment error. Please contact support if issue persists."}
`

**Comment by StephenJosey** [comment]
Ah, well there's the issue. So before you removed the "/" it just wasn't finding the page (so it was presumably trying to return a default 404 HTML page which can't be decoded into json).

Now that it's working, Square is informing you that your account isn't enabled for payments. Basically, you need to login to your Square account and complete the IDV process in order to make production transactions. Once you do that, it should work successfully. Alternatively, you should be able to use your sandbox credentials to do a test transaction. Please let me know if that doesn't work, though.

**Comment by mikeyyg96** [comment]
@StephenJosey Okay I will try in Sandbox when I get home. In the meantime, you know a link on where to complete the IDV process. I searched on google "Square IDV" and nothing about completing something came up.

**Comment by StephenJosey** [comment]
No problem, sorry about that! Go ahead and login to the [Square Dashboard](https://squareup.com/dashboard/) and then click on "Setup Guide" and you should see an option for "Get Paid" and then "Verify your identity".

**Comment by mikeyyg96** [comment]
Ok I completed the Setup Guide successfully. I did another attempt at transaction and the log is different, but still outputting an error I think. My code still gives FormatException as well when I try to decode it. 

```
Future<String> _makeCharge(CardDetails cardDetails) async{
    String chargeServerHost = "https://links-app-maginate.herokuapp.com";
    String chargeUrl = "$chargeServerHost/chargeForCookie";

    await chargeCard(cardDetails, chargeUrl);
    
    return null;
  }

  Future<void> chargeCard(CardDetails result, String chargeUrl) async {
    var body = jsonEncode({"nonce": result.nonce});
    print('debug: body is $body');
    http.Response response;
    try {
      response = await http.post(chargeUrl, body: body, headers: {
        "Accept": "application/json",
        "content-type": "application/json"
      });
      print('(debug) response.body is: ${response.body}');
    } on SocketException catch (ex) {
      throw ChargeException(ex.message);
    }

    var responseBody = json.decode(response.body); // FormatException occurs 
    if (response.statusCode == 200) {
      return;
    } else {
      throw ChargeException(responseBody["errorMessage"]);
    }
  }

```
```
I/flutter (23117): debug: body is {"nonce":"cnon:CBASEP2AWXOArc4KuHtTfF8DESY"}
I/flutter (23117): (debug) response.body is: <!DOCTYPE html>
```


```
2019-08-29T21:07:34.530496+00:00 heroku[web.1]: Idling
2019-08-29T21:07:34.535301+00:00 heroku[web.1]: State changed from up to down
2019-08-29T21:07:35.261588+00:00 heroku[web.1]: Stopping all processes with SIGTERM
2019-08-29T21:07:35.361310+00:00 heroku[web.1]: Process exited with status 143
2019-08-30T01:07:05.961352+00:00 heroku[web.1]: State changed from down to starting
2019-08-30T01:07:08.524140+00:00 heroku[web.1]: Starting process with command `npm start`
2019-08-30T01:07:10.500712+00:00 app[web.1]: 
2019-08-30T01:07:10.500733+00:00 app[web.1]: > quickstart-mobile-server@1.0.0 start /app
2019-08-30T01:07:10.500735+00:00 app[web.1]: > node index.js
2019-08-30T01:07:10.500737+00:00 app[web.1]: 
2019-08-30T01:07:11.088341+00:00 app[web.1]: Your app is listening on port 47671
2019-08-30T01:07:11.884203+00:00 heroku[web.1]: State changed from starting to up
2019-08-30T01:07:13.122909+00:00 app[web.1]: (node:22) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'req' of undefined
2019-08-30T01:07:13.122928+00:00 app[web.1]:     at app.post (/app/index.js:66:23)
2019-08-30T01:07:13.122931+00:00 app[web.1]:     at <anonymous>
2019-08-30T01:07:13.122934+00:00 app[web.1]:     at process._tickCallback (internal/process/next_tick.js:189:7)
2019-08-30T01:07:13.123073+00:00 app[web.1]: (node:22) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
2019-08-30T01:07:13.123185+00:00 app[web.1]: (node:22) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
2019-08-30T01:07:43.070872+00:00 heroku[router]: at=error code=H12 desc="Request timeout" method=POST path="/chargeForCookie" host=links-app-maginate.herokuapp.com request_id=dd3e1bae-17c3-4f60-8b07-991ef10e5491 fwd="73.52.103.100" dyno=web.1 connect=0ms service=30001ms status=503 bytes=0 protocol=https

```

**Comment by mikeyyg96** [comment]
@StephenJosey Nevermind, I finally got it working. After I completed the Setup Guide (that definitely helped), I looked into my config vars on Heroku and removed the quotations around the value of the API_BASE_PATH. The documentation should specify that because I wasn't sure whether to add the quotations or not and it was just trial and error.

**Comment by jawad12345A** [comment]
I am also facing this issue can you tell me .How you solved it?
